# Conclusion
## Main Takeaways
Our Exploratory Data Analysis revealed significant correlations between salary levels and factors like agency name, job title, work location, agency size, job type and overtime hours & overtime pay. We highlighted how different agencies and job titles influence salary levels, how different salary performance in different regions in New York with particular attention to overtime payments and duration. 
In our project, we divide the analysis into 2 parts. Here we summarize the important conclusions.  In terms of part 1 - Base Salary, we gain the top 3 agencies with high annual salaries which are the department of ED Pedagogical, Fire Department, Police Department where teacher, teacher special education are also in the top 3 base salary among all job titles. It’s worth noting that the computer specialist does not belong to agencies with a high salary, but this job has the highest salary among all job titles. The salary distribution of various agencies reveal diverse patterns. With agencies like the Department of Finance and Fire Department mostly concentrated in the lower to mid salary ranges (40,000 to 80,000 dollars), while others like the Dept of Ed Pedagogical feature many higher-end salaries (near 100,000 dollars).
Moreover, in the last 10 years, the salary of all agencies and job titles show an upward trend but the salary data across different titles shows remarkable variation. Additionally, Manhattan has the highest annual salary among all other regions in New York. 
In terms of part 2 - Overtime hours and salary, we discover that the agencies like department of finance, department of Info Tech, Taxi commission have low overtime hours and department of pedagogical even doesn’t have overtime, while fire department has the most overtime hours especially for firefighters. Besides, the department of sanitation, fire department, and police department have high overtime pay and the job title police dominates, while the department of finance has lowest overtime pay.  Job titles like police officers and firefighters often correlate with higher overtime pay and hours, and they vary significantly with each other, whereas departments like Social Service, and Children's Services show more uniform OT pay distributions. From 2022 to the present, the overtime hours show a downward trend and overtime pay shows an upward trend, except the decreasing overtime pay in the Taxi & Limousine Commission. It indicates that the government is paying attention to the quality of life of the people. Additionally, Manhattan has  the lowest overtime rate.
When we consider both base salary and overtime pay, there are distinct patterns, with some roles like emergency medical specialists showing high values in both, while others like sanitation workers have high salaries but shorter overtime hours. Conversely, roles like sanitation workers, despite high salaries, often see fewer overtime hours, suggesting a different compensation structure in these positions.

## Limitations 
This study faced some limitations. First, we only use one dataset as our source which may lead to potential biases. Second, the factors impacting salary are not enough and we lack the data related to the personal informationn, so it may hide some relationship between Salary & Overtime and factors like leave status, regular gross paid in our original data set. Third, our data exploratory has limited generalizability because it only focuses on the agencies and job titles with higher employees in New York, so our conclusion may not be proper for all employees in New York. Fourth, due to the large number of dataset, some graphs may not include all the employees in order to have a clear graph and our method of random sample is default, which may lead to missing patterns.

## Future Directions 
Future research directions include a deeper exploration of causal relationships between salary & overtime and other factors which are not included in our analysis including. It will be better if we add more quantitative analysis to our numerical data visualization like more accurate distribution based on histogram. Besides, we intend to expand the variable scope and incorporate more diverse and comprehensive datasets related to salary from other sources where we can make comparisons with each other such as using national standard salary based on different people as a reference.

## Lessons Learned
Our data set has the complexity of salary structures and influence of multifaceted factors. Due to its complexity, it is more important for us to have data preprocessing, interpretation, and comprehensive statistical analysis in understanding compensation trends. Considering data preparation, we should realize that blank space cannot be recognized by missing value detection. Besides, it will be easier if we finish all new column establishment in the beginning. As for data interpretation, we should pay attention that some data has representativeness, but these data may also have limitations. Furthermore, when we analyze the data by visualization, we should not only analyze the numbers but also understand the context, the underlying trends, and what they signify in the broader spectrum.
