# Results

```{r}
library(tidyverse)
salary_df <- read.csv("Cleaned Dataset.csv")
```

```{r}
select_agency <- salary_df |> 
  filter(Agency.Name == c('DEPT OF ED PEDAGOGICAL','POLICE DEPARTMENT',
'FIRE DEPARTMENT',
'HRA/DEPT OF SOCIAL SERVICES',
'NYC HOUSING AUTHORITY',
 'DEPARTMENT OF SANITATION',
"ADMIN FOR CHILDREN'S SVCS",
'DEPARTMENT OF FINANCE',
'DEPT OF INFO TECH & TELECOMM',
'TAXI & LIMOUSINE COMMISSION'))
```

```{r}
select_title <- select_agency |>  
  filter(Title.Description %in% c("CHILD PROTECTIVE SPECIALIST",
                                  "CHILD PROTECTIVE SPECIALIST SUPERVISOR",
                                  "CITY TAX AUDITOR",
                                  "CLERICAL ASSOCIATE",
                                  "CALL CENTER REPRESENTATIVE",
                                  "COMPUTER SPECIALIST",
                                  "TAXI AND LIMOUSINE INSPECTOR",
                                  "COMMUNITY ASSOCIATE",
                                  "TEACHER",
                                  "TEACHER SPECIAL EDUCATION",
                                  "POLICE OFFICER",
                                  "SCHOOL SAFETY AGENT",
                                  "FIREFIGHTER",
                                  "EMERGENCY MEDICAL SPECIALIST-EMT",
                                  "ELIGIBILITY SPECIALIST",
                                  "JOB OPPORTUNITY SPECIALIST",
                                  "CARETAKER",
                                  "MAINTENANCE WORKER",
                                  "SANITATION WORKER",
                                  "CITY SEASONAL AIDE"))
```

```{r Salary Level}
library(dplyr)
df <- select_title |>  
  mutate(AnnualSalary = case_when(
    Pay.Basis == "per Annum" ~ 1,
    Pay.Basis == "per Day" ~ 260,
    Pay.Basis == "per Hour" ~ 260 * 8,
    Pay.Basis == "Prorated Annual" ~ 1
  ))

salary_new <- df |> 
  mutate(AnnualSalary = AnnualSalary * Base.Salary)

fivenum(salary_new$AnnualSalary)
# 6461  58692  80788  95105 143858

salary_new <- salary_new |>
  mutate(SalaryLevel = case_when(
    AnnualSalary >= 6461 & AnnualSalary <= 58692 ~ "LOW",
    AnnualSalary > 58692 & AnnualSalary <= 80788 ~ "MOD",
    AnnualSalary > 80788 & AnnualSalary <= 95105 ~ "HIGH",
    AnnualSalary > 95105 & AnnualSalary <= 143858 ~ "VHIGH"))
```

```{r Agency Start Time}
salary_new$Agency.Start.Date <- trimws(salary_new$Agency.Start.Date)
salary_new$Agency.Start.Date <- as.Date(salary_new$Agency.Start.Date, format="%m/%d/%Y")
salary_new$CorrentDate <- as.Date("2023-12-01")

salary_new$Agency.Start.Date[salary_new$Agency.Start.Date == as.Date("9999-12-31")] <- as.Date("1999-12-31")

salary_new$days_difference <- as.Date(salary_new$CorrentDate) - as.Date(salary_new$Agency.Start.Date)
salary_new$days_difference <- as.numeric(salary_new$days_difference)
```

```{r total pay_per_hour and agency_size}
salary_new$OT.Hours[salary_new$OT.Hours<0]<-0
salary_new$Regular.Hours[salary_new$Regular.Hours<0]<-0

salary_new$pay_per_hour<-salary_new$Total.OT.Paid/salary_new$OT.Hours
salary_new$pay_per_hour[is.infinite(salary_new$pay_per_hour)| is.na(salary_new$pay_per_hour) |salary_new$pay_per_hour<0] <- 0 


salary_new$job_type <- ifelse(as.numeric(salary_new$Regular.Hours) <= 1000 & as.numeric(salary_new$Regular.Hours) > 0, "part_time", "full_time")

agency_size <- as.data.frame(table(salary_new$Agency.Name))
colnames(agency_size) <- c("Agency.Name", "Agency.Size")
salary <- left_join(salary_new, agency_size, by = join_by(Agency.Name))
```

```{r}
count_by_columnB <- salary %>%
  group_by(job_type) %>%
  summarise(Count = n())
print(count_by_columnB)
```

```{r Correlation Heatmap Plot for Categorical Variables}
# library(dplyr)
library(GGally)
p <- salary_new[, c(2, 4:6, 8, 15)]
library(ggcorrplot)
model.matrix(~0+., data=p) %>%
  cor(use="pairwise.complete.obs") %>%
  ggcorrplot(show.diag=FALSE, type="lower", lab=FALSE, lab_size=2)+
  theme(axis.text.x = element_text(size = 5),  # Adjust size as needed for x axis labels
        axis.text.y = element_text(size = 5))
# p <- salary_new[, c(2, 4:6, 8, 15)]
# ggparcoord(p, columns=1:6)
```
**Observation and Analysis:**
We want to find the relationship between 

```{r Scattor Pair Plot for Continous Variables}
ggpairs(select(salary, Agency.Size, days_difference, AnnualSalary), 
        mapping = ggplot2::aes(alpha = 0.5),
        lower = list(continuous = wrap("points", size = 0.1)))
```

```{r Lollipop}
library(gridExtra)
q <- salary_new[, c(2, 5, 14)]
mean_salary_agency <- q %>%
    group_by(Agency.Name) %>%
    summarise(mean_value_agency = mean(AnnualSalary, na.rm = TRUE))

mean_salary_title <- q %>%
    group_by(Title.Description) %>%
    summarise(mean_value_title = mean(AnnualSalary, na.rm = TRUE))

ggplot(mean_salary_agency, aes(x=Agency.Name, y=mean_value_agency)) +
  geom_segment( aes(x=Agency.Name, xend=Agency.Name, y=0, yend=mean_value_agency)) +
  geom_point( size=5, color="red", fill=alpha("orange", 0.3), alpha=0.7, shape=21, stroke=2)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(mean_salary_title, aes(x=Title.Description, y=mean_value_title)) +
  geom_segment( aes(x=Title.Description, xend=Title.Description, y=0, yend=mean_value_title)) +
  geom_point( size=5, color="red", fill=alpha("orange", 0.3), alpha=0.7, shape=21, stroke=2)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r Map for Mean Salary}
library(sf)
library(tigris)

nyc_counties <- tigris::counties(state = "NY", cb = TRUE) %>% 
  filter(COUNTYFP %in% c("005", "047", "061", "081", "085"))  # FIPS codes for NYC boroughs


nyc_counties$BoroName <- factor(nyc_counties$NAME,
                                levels = c("Bronx", "Kings", "New York", "Queens", "Richmond"),
                                labels = c("BRONX", "BROOKLYN", "MANHATTAN", "QUEENS", "RICHMOND"))

OThour_data <- salary %>%
  group_by(Work.Location.Borough) %>%
  summarize(Average_salary = mean(AnnualSalary, na.rm = TRUE))


nyc_OThour_map <- merge(nyc_counties, OThour_data, by.x = "BoroName", by.y = "Work.Location.Borough")

# Create the map visualization
ggplot(data = nyc_OThour_map) +
  geom_sf(aes(fill = Average_salary), color = "white", size = 0.5) +
  geom_sf_text(aes(label = BoroName), size = 3, check_overlap = TRUE) +
  scale_fill_viridis_c(name = "Average Hour") +
  labs(title = "Average Hour by NYC Borough") +
  theme_minimal()


df_aggregated <- aggregate(AnnualSalary ~ Work.Location.Borough, data = salary, mean)

coordinates <- data.frame(
  Work.Location.Borough = c("MANHATTAN", "BROOKLYN", "BRONX", "QUEENS", "RICHMOND", "OTHER"),
  x = c(-73.9712, -73.9442, -73.8648, -73.7949, -74.1502, -74.0060),  # Longitude
  y = c(40.7831, 40.6782, 40.8448, 40.7282, 40.5795, 40.7128)         # Latitude
)

df_merged <- merge(df_aggregated, coordinates, by = "Work.Location.Borough")

ggplot(df_merged, aes(x = x, y = y, size = AnnualSalary)) +
    geom_point(alpha = 0.5, color = "pink") +
    geom_text(aes(label = Work.Location.Borough), vjust = -1.5, size = 3.5) +  # Place text above the circles
    scale_size(range = c(10, 35)) +
    theme_void() +
    labs(title = "Average Salary by NYC Borough")
```

```{r Time Series for Mean Salary}
average_salary_agency <- salary %>%
  group_by(Agency.Name, Fiscal.Year) %>%
  summarise(average_salary = mean(AnnualSalary, na.rm = TRUE), .groups = 'drop')

average_salary_agency |>
  ggplot(aes(x=Fiscal.Year, y=average_salary, group=Agency.Name, color=Agency.Name)) +
    geom_line()

average_salary_title <- salary %>%
  group_by(Title.Description, Fiscal.Year) %>%
  summarise(average_salary = mean(AnnualSalary, na.rm = TRUE), .groups = 'drop')

average_salary_title |> 
  ggplot(aes(x=Fiscal.Year, y=average_salary, group=Title.Description, color=Title.Description)) +
    geom_line()
```

```{r Histogram for Mean Salary}
ggplot(average_salary_agency, aes(x = average_salary)) +
  geom_histogram(binwidth = 1000, fill = "lightblue", color = "black") +
  facet_wrap(~Agency.Name) + 
  theme(strip.text.x = element_text(size = 7))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplot(average_salary_title, aes(x = average_salary)) +
  geom_histogram(binwidth = 2000, fill = "lightblue", color = "black") +
  facet_wrap(~Title.Description) + 
  theme(strip.text.x = element_text(size = 7))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```



```{r Box Plot}
library(ggplot2)
ggplot(salary, aes(x = Agency.Name, y = OT.Hours)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Box Plot of OT.Hours across Different Agencies",
       x = "Agency Name",
       y = "OT Hours")

ggplot(salary, aes(x = Title.Description, y = OT.Hours)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Box Plot of OT.Hours across Different Titles",
       x = "Title Description",
       y = "OT Hours")

ggplot(salary, aes(x = job_type, y = OT.Hours)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Box Plot of OT.Hours across Different Titles",
       x = "Job_type",
       y = "OT Hours")

salary_tep2<-salary
salary_tep2<-salary_tep2[salary_tep2$pay_per_hour > 0 & salary_tep2$pay_per_hour <150, ]



ggplot(salary_tep2, aes(x = Agency.Name, y = pay_per_hour)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Box Plot of pay_per_hour across Different Agencies",
       x = "Agency Name",
       y = "OT Pay per Hours")

ggplot(salary_tep2, aes(x = Title.Description, y = pay_per_hour)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Box Plot of pay_per_hour across Different Titles",
       x = "Title Description",
       y = "OT Pay per Hours")

ggplot(salary_tep2, aes(x = job_type, y = pay_per_hour)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Box Plot of pay_per_hour across Different Titles",
       x = "Job_type",
       y = "OT Pay per Hours")


# ANOVA for Agency.Name and OT.Hours
anova_agency <- aov(OT.Hours ~ Agency.Name, data = salary)
summary(anova_agency)

# ANOVA for Title.Description and OT.Hours
anova_title <- aov(OT.Hours ~ Title.Description, data = salary)
summary(anova_title)

# ANOVA for job_type and OT.Hours
anova_title <- aov(OT.Hours ~ job_type, data = salary)
summary(anova_title)


# ANOVA for Agency.Name and Total.OT.Paid
anova_agency <- aov(pay_per_hour ~ Agency.Name, data = salary_tep2)
summary(anova_agency)

# ANOVA for Title.Description and Total.OT.Paid
anova_title <- aov(pay_per_hour ~ Title.Description, data = salary_tep2)
summary(anova_title)

# ANOVA for job_title and Total.OT.Paid
anova_title <- aov(pay_per_hour ~ job_type, data = salary_tep2)
summary(anova_title)
```

```{r Parallell}
library(GGally)
ggparcoord(salary,
           columns = c(11,18,17),  groupColumn = 5,
           scale='globalminmax',
           title = "Parallel Coordinate Plot for salary Data",
           alphaLines = 0.6)
ggparcoord(salary,
           columns = c(11,18,17),  groupColumn = 4,
           scale='globalminmax',
           title = "Parallel Coordinate Plot for salary Data",
           alphaLines = 0.6)
```

#police


```{r Map}

library(sf)
library(tigris)


# Obtain geospatial data for New York counties
nyc_counties <- tigris::counties(state = "NY", cb = TRUE) %>% 
  filter(COUNTYFP %in% c("005", "047", "061", "081", "085"))  # FIPS codes for NYC boroughs


nyc_counties$BoroName <- factor(nyc_counties$NAME,
                                levels = c("Bronx", "Kings", "New York", "Queens", "Richmond"),
                                labels = c("BRONX", "BROOKLYN", "MANHATTAN", "QUEENS", "RICHMOND"))

OThour_data <- salary %>%
  group_by(Work.Location.Borough) %>%
  summarize(Average_hour = mean(OT.Hours, na.rm = TRUE))


nyc_OThour_map <- merge(nyc_counties, OThour_data, by.x = "BoroName", by.y = "Work.Location.Borough")
#View(nyc_OThour_map) 

# Create the map visualization
ggplot(data = nyc_OThour_map) +
  geom_sf(aes(fill = Average_hour), color = "white", size = 0.5) +
  geom_sf_text(aes(label = BoroName), size = 3, check_overlap = TRUE) +
  scale_fill_viridis_c(name = "Average Hour") +
  labs(title = "Average Hour by NYC Borough") +
  theme_minimal()


OTpay_perhour <- salary_tep2 %>%
  group_by(Work.Location.Borough) %>%
  summarize(Averagepay_perhour = mean(pay_per_hour, na.rm = TRUE))


nyc_OTpay_perhour_map <- merge(nyc_counties, OTpay_perhour, by.x = "BoroName", by.y = "Work.Location.Borough")
#View(nyc_OThour_map) 

# Create the map visualization
ggplot(data = nyc_OTpay_perhour_map ) +
  geom_sf(aes(fill = Averagepay_perhour), color = "white", size = 0.5) +
  geom_sf_text(aes(label = BoroName), size = 3, check_overlap = TRUE) +
  scale_fill_viridis_c(name = "Average pay per Hour") +
  labs(title = "Average pay per Hour by NYC Borough") +
  theme_minimal()
```

```{r Time Series}
averageOThour_by_group  <- salary %>%
  group_by(Agency.Name, Fiscal.Year) %>%
  summarize(Average_hour = mean(OT.Hours, na.rm = TRUE))
averageOThour_by_group |>
  ggplot(aes(x=Fiscal.Year, y=Average_hour, group=Agency.Name, color=Agency.Name)) +
    geom_line()


averageOTpay_perhour_by_group  <- salary %>%
  group_by(Agency.Name, Fiscal.Year) %>%
  summarize(Average_OTpay = mean(pay_per_hour, na.rm = TRUE))
averageOTpay_perhour_by_group |>
  ggplot(aes(x=Fiscal.Year, y=Average_OTpay, group=Agency.Name, color=Agency.Name)) +
    geom_line()
```

```{r Ridgeline}
library(ggridges)

ggplot(salary, aes(x = OT.Hours, y = Agency.Name, fill = Agency.Name)) +
  stat_density_ridges() +
  theme_ridges() +
  labs(title = "Ridgeline Plot of OT Hours by Agency", x = "OT Hours", y = "Agency Name")+
    theme(
    text = element_text(size = 8),
    axis.title = element_text(size = 10),
    axis.text = element_text(size = 8),
    plot.title = element_text(size = 12)
  )


####revise
ggplot(salary, aes(x = Total.OT.Paid, y = Agency.Name, fill = Agency.Name)) +
  stat_density_ridges() +
  theme_ridges() +
  labs(title = "Ridgeline Plot of OT Hours Paid by Agency", x = "OT Hours Paid", y = "Agency Name")+
    theme(
    text = element_text(size = 8),
    axis.title = element_text(size = 10),
    axis.text = element_text(size = 8),
    plot.title = element_text(size = 12)
  )


salary_tep<-salary
salary_tep<-salary_tep[salary_tep$Regular.Hours != 0, ]
salary_tep$OT_per_Regular_Time<-salary_tep$OT.Hours/salary_tep$Regular.Hours



ggplot(salary_tep, aes(x = OT_per_Regular_Time, y = Agency.Name, fill = Agency.Name)) +
  stat_density_ridges() +
  theme_ridges() +
  labs(title = "Ridgeline Plot of OT Hours rate by Agency", x = "OT Hours rate", y = "Agency Name")+
    theme(
    text = element_text(size = 8),
    axis.title = element_text(size = 10),
    axis.text = element_text(size = 8),
    plot.title = element_text(size = 12)
  )

```

```{r Bubble}

salary_tep2<-salary
salary_tep2<-salary_tep2[salary_tep2$pay_per_hour > 0, ]

set.seed(123)
sampled_indices <- sample(nrow(salary_tep2),150)
sampled_df <- salary_tep2[sampled_indices, ]

sampled_df %>%
  arrange(desc(days_difference)) %>%
  ggplot(aes(x=OT.Hours, y=pay_per_hour, size=days_difference, color=Title.Description)) +
    geom_point(alpha=0.5) +
    scale_size_continuous(range = c(.1, 10), name="days_difference")

sampled_df %>%
  arrange(desc(days_difference)) %>%
  ggplot(aes(x=AnnualSalary, y=OT.Hours, size=days_difference, color=Title.Description)) +
    geom_point(alpha=0.5) +
    scale_size_continuous(range = c(.1, 10), name="days_difference")

sampled_df %>%
  arrange(desc(days_difference)) %>%
  ggplot(aes(x=AnnualSalary, y=pay_per_hour, size=days_difference, color=Title.Description)) +
    geom_point(alpha=0.5) +
    scale_size_continuous(range = c(.1, 10), name="days_difference")

```



```{r Ggalluvial}
library(ggalluvial)
frequency_df <- salary %>%
  group_by(Agency.Name, Title.Description, job_type, Work.Location.Borough,SalaryLevel) %>%
  summarize(Frequency = n(), .groups = 'drop')
frequency_df


ggplot(frequency_df, aes(axis1 = Agency.Name, axis2 = Title.Description, axis3 = job_type, axis4 = Work.Location.Borough, axis5 = SalaryLevel, y = Frequency)) +
  geom_alluvium(aes(fill = Agency.Name)) +  # Using one variable for fill, you can change it as per your need
  geom_stratum(aes(fill = Agency.Name)) +  # Optional: Add color to stratum
  geom_text(stat = "stratum", aes(label = after_stat(stratum)),size=1.5) +
  scale_x_discrete(limits = c("Agency.Name", "Title.Description", "job_type", "Work.Location.Borough", "SalaryLevel")) +
  guides(fill = "none")  # If you want a legend for the colors, remove this line

```
